common: &psql
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *psql
  database: tippspiel_dev
  username: tippspiel
  password: linomail

test:
  <<: *psql
  database: tippspiel_test
  username: tippspiel
  password: linomail

production:
  <<: *psql
  database: tippspiel_production
  username: tippspiel
  password: linomail
